services:
  api-gateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "50051:50051"
